USE hospital_management;

-- ─────────────────────────────────────────────
--  STORED PROCEDURES
-- ─────────────────────────────────────────────

DELIMITER $$

-- ── sp_add_appt ──────────────────────────────────────────────────────────────
-- Create a new appointment after validating that both DoctorID and PatientID exist.
-- Parameters:
--   p_AppointmentID  : appointment identifier (auto-generated by Python layer)
--   p_DoctorID       : must exist in Doctors table
--   p_PatientID      : must exist in Patients table
--   p_Date           : appointment date (DATE)
--   p_Time           : appointment time (TIME)
--   p_Message (OUT)  : result message returned to caller

DROP PROCEDURE IF EXISTS sp_add_appt $$
CREATE PROCEDURE sp_add_appt (
    IN  p_AppointmentID VARCHAR(20),
    IN  p_DoctorID      VARCHAR(20),
    IN  p_PatientID     VARCHAR(20),
    IN  p_Date          DATE,
    IN  p_Time          TIME,
    OUT p_Message       VARCHAR(100)
)
BEGIN
    DECLARE doc_exist INT DEFAULT 0;
    DECLARE pat_exist INT DEFAULT 0;

    SELECT COUNT(*) INTO doc_exist FROM Doctors  WHERE DoctorID  = p_DoctorID;
    SELECT COUNT(*) INTO pat_exist FROM Patients WHERE PatientID = p_PatientID;

    IF doc_exist = 0 THEN
        SET p_Message = 'ERROR: DoctorID does not exist.';
    ELSEIF pat_exist = 0 THEN
        SET p_Message = 'ERROR: PatientID does not exist.';
    ELSE
        INSERT INTO Appointments (AppointmentID, AppointmentDate, AppointmentTime, DoctorID, PatientID)
        VALUES (p_AppointmentID, p_Date, p_Time, p_DoctorID, p_PatientID);
        SET p_Message = CONCAT('Appointment created successfully. ID: ', p_AppointmentID);
    END IF;
END $$


-- ── sp_gen_inv ───────────────────────────────────────────────────────────────
-- Generate a new invoice after validating that the patient exists and amount > 0.
-- Parameters:
--   p_InvoiceID      : invoice identifier (auto-generated by Python layer)
--   p_PatientID      : must exist in Patients table
--   p_Amount         : billing amount; must be positive
--   p_Message (OUT)  : result message returned to caller

DROP PROCEDURE IF EXISTS sp_gen_inv $$
CREATE PROCEDURE sp_gen_inv (
    IN  p_InvoiceID  VARCHAR(20),
    IN  p_PatientID  VARCHAR(20),
    IN  p_Amount     DECIMAL(15, 2),
    OUT p_Message    VARCHAR(100)
)
BEGIN
    DECLARE pat_exist INT DEFAULT 0;

    SELECT COUNT(*) INTO pat_exist FROM Patients WHERE PatientID = p_PatientID;

    IF pat_exist = 0 THEN
        SET p_Message = 'ERROR: PatientID does not exist.';
    ELSEIF p_Amount <= 0 THEN
        SET p_Message = 'ERROR: Amount must be greater than zero.';
    ELSE
        INSERT INTO Invoices (InvoiceID, InvoiceDate, TotalAmount, PatientID)
        VALUES (p_InvoiceID, CURDATE(), p_Amount, p_PatientID);
        -- Fixed: use parameter p_InvoiceID, not the column name InvoiceID
        SET p_Message = CONCAT('Invoice created. ID: ', p_InvoiceID,
                               ' — Amount: ', FORMAT(p_Amount, 0), ' VND');
    END IF;
END $$


-- ── sp_revenue_report ────────────────────────────────────────────────────────
-- Return a daily billing summary between two dates.
-- Used by the Python reporting module (_report_billing_summary).

DROP PROCEDURE IF EXISTS sp_revenue_report $$
CREATE PROCEDURE sp_revenue_report (
    IN p_StartDate DATE,
    IN p_EndDate   DATE
)
BEGIN
    SELECT
        InvoiceDate,
        COUNT(*)                    AS InvoiceCount,
        FORMAT(SUM(TotalAmount), 0) AS TotalBilled,
        FORMAT(AVG(TotalAmount), 0) AS AveragePerInvoice
    FROM Invoices
    WHERE InvoiceDate BETWEEN p_StartDate AND p_EndDate
    GROUP BY InvoiceDate
    ORDER BY InvoiceDate;
END $$

DELIMITER ;
